import { ImageSourcePropType } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import { ThemeColors, ThemeMode } from '../types/theme';

export interface ThemeCardData {
  id: ThemeMode;
  code: string;
  badge: string;
  subtitle: string;
  title: string;
  desc: string;
  icon: keyof typeof MaterialIcons.glyphMap;
  swatches: string[];
  image: ImageSourcePropType;
}

export const THEME_LIST: ThemeCardData[] = [
  {
    id: 'rainy',
    code: '01 / RAINY',
    badge: 'Nuansa Hujan',
    subtitle: '#3A4D5E • #70C5E8',
    title: 'Langit Mendung & Rintik Tenang',
    desc: 'Suasana tenang, sejuk, dan fokus dengan efek visual rintik air pixel pada bilah header. Sempurna untuk deep work tanpa distraksi.',
    icon: 'water-drop',
    swatches: ['#3A4D5E', '#7B92A8', '#70C5E8', '#EAF6FD'],
    image: require('../../assets/pixel/theme_rainy.jpg'),
  },
  {
    id: 'starry',
    code: '02 / NIGHT',
    badge: 'Malam Berbintang',
    subtitle: '#171A2E • #FFDE59',
    title: 'Hening Damai & Cahaya Bulan',
    desc: 'Hening dan damai, sangat ideal untuk sesi malam, journaling, dan refleksi harian dengan aksen bintang keemasan pixel.',
    icon: 'nights-stay',
    swatches: ['#171A2E', '#282A4A', '#FFDE59', '#7367F0'],
    image: require('../../assets/pixel/theme_starry.jpg'),
  },
  {
    id: 'windy',
    code: '03 / BREEZE',
    badge: 'Nuansa Berangin',
    subtitle: '#56B4D3 • #88D49E',
    title: 'Angin Berhembus & Daun Terbang',
    desc: 'Dinamis, bersemangat, segar dan aktif. Menyertakan partikel dedaunan hijau-keemasan yang meluncur di sela-sela kartu agenda.',
    icon: 'air',
    swatches: ['#56B4D3', '#A5E2E8', '#88D49E', '#F3C969'],
    image: require('../../assets/pixel/theme_windy.jpg'),
  },
  {
    id: 'snow',
    code: '04 / FROST',
    badge: 'Nuansa Bersalju',
    subtitle: '#EAF6FD • #88CEEB',
    title: 'Kristal Es & Bukit Berselimut',
    desc: 'Dingin, bersih, minimalis, dan tentram. Mengganti latar jadwal dengan palet salju pastel yang jernih dan menenangkan mata.',
    icon: 'ac-unit',
    swatches: ['#EAF6FD', '#88CEEB', '#D4EFFC', '#3076AB'],
    image: require('../../assets/pixel/theme_snow.jpg'),
  },
  {
    id: 'default',
    code: '00 / CLASSIC',
    badge: 'Hijau Berawan',
    subtitle: '#006B31 • #EAFEEF',
    title: 'Retro Hijau & Awan Klasik (Default)',
    desc: 'Palet asli HAYA 16-bit dengan perpaduan hijau mint segar dan estetika retro produktivitas gameboy klasik.',
    icon: 'cloud',
    swatches: ['#006b31', '#198643', '#77db8e', '#eafeef'],
    image: require('../../assets/pixel/avatar.png'),
  },
];

export const THEMES: Record<ThemeMode, ThemeColors> = {
  default: {
    name: 'Hijau Berawan (Default)',
    weatherTitle: 'Cerah Berawan',
    weatherDesc: 'Udara sejuk dengan awan pixel ramah',
    weatherIcon: 'cloud',
    tempText: '26°C • Berangin',
    surface: '#eafeef',
    surfaceContainer: '#def3e4',
    surfaceContainerLow: '#e4f9ea',
    surfaceContainerHigh: '#d9edde',
    surfaceContainerLowest: '#ffffff',
    surfaceDim: '#cbdfd1',
    onSurface: '#0e1f16',
    onSurfaceVariant: '#3f4a3f',
    primary: '#006b31',
    onPrimary: '#ffffff',
    primaryContainer: '#198643',
    onPrimaryContainer: '#f7fff3',
    secondary: '#486554',
    onSecondary: '#ffffff',
    secondaryContainer: '#c7e7d2',
    onSecondaryContainer: '#4c6958',
    tertiary: '#755700',
    tertiaryFixed: '#ffdf9d',
    onTertiaryFixed: '#251a00',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#112219',
    divider: '#c7e7d2',
    shadow: '#112219',
    cardBg: '#ffffff',
    accentSwatches: ['#006b31', '#198643', '#77db8e', '#eafeef'],
  },
  rainy: {
    name: 'Rainy (Mendung & Rintik)',
    weatherTitle: 'Hujan Rintik',
    weatherDesc: 'Suasana tenang, sejuk, dan fokus dengan rintik air pixel',
    weatherIcon: 'water_drop',
    tempText: '22°C • Hujan Rintik',
    surface: '#EAF6FD',
    surfaceContainer: '#D3E7F4',
    surfaceContainerLow: '#DFEFF9',
    surfaceContainerHigh: '#C7DFEE',
    surfaceContainerLowest: '#FFFFFF',
    surfaceDim: '#BFD7E6',
    onSurface: '#16232D',
    onSurfaceVariant: '#3A4D5E',
    primary: '#245B7D',
    onPrimary: '#FFFFFF',
    primaryContainer: '#3A749B',
    onPrimaryContainer: '#F0F8FF',
    secondary: '#507085',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#BCD9EC',
    onSecondaryContainer: '#224053',
    tertiary: '#70C5E8',
    tertiaryFixed: '#C0EAFC',
    onTertiaryFixed: '#0A384D',
    error: '#C0392B',
    onError: '#FFFFFF',
    border: '#13212B',
    divider: '#BFD7E6',
    shadow: '#13212B',
    cardBg: '#FFFFFF',
    accentSwatches: ['#3A4D5E', '#7B92A8', '#70C5E8', '#EAF6FD'],
  },
  starry: {
    name: 'Starry Sky (Malam Berbintang)',
    weatherTitle: 'Malam Berbintang',
    weatherDesc: 'Hening dan damai, ideal untuk deep work malam hari',
    weatherIcon: 'nights_stay',
    tempText: '20°C • Langit Hening',
    surface: '#1A1C33',
    surfaceContainer: '#242745',
    surfaceContainerLow: '#1E213D',
    surfaceContainerHigh: '#2D3154',
    surfaceContainerLowest: '#14162B',
    surfaceDim: '#121426',
    onSurface: '#EDEDF8',
    onSurfaceVariant: '#A4A8D1',
    primary: '#7367F0',
    onPrimary: '#FFFFFF',
    primaryContainer: '#594FCE',
    onPrimaryContainer: '#FAF9FF',
    secondary: '#5A5F8C',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#353960',
    onSecondaryContainer: '#D0D3F8',
    tertiary: '#FFDE59',
    tertiaryFixed: '#FFEBA0',
    onTertiaryFixed: '#2B2300',
    error: '#FF5C5C',
    onError: '#FFFFFF',
    border: '#0A0B16',
    divider: '#353960',
    shadow: '#0A0B16',
    cardBg: '#21243F',
    accentSwatches: ['#171A2E', '#282A4A', '#FFDE59', '#7367F0'],
  },
  windy: {
    name: 'Windy (Nuansa Berangin)',
    weatherTitle: 'Angin Segar',
    weatherDesc: 'Dinamis, bersemangat, segar dan aktif dengan partikel daun',
    weatherIcon: 'air',
    tempText: '25°C • Berhembus Kencang',
    surface: '#EFFBF7',
    surfaceContainer: '#D7F3EA',
    surfaceContainerLow: '#E3F8F1',
    surfaceContainerHigh: '#C9EFE2',
    surfaceContainerLowest: '#FFFFFF',
    surfaceDim: '#BEE7D8',
    onSurface: '#0E261E',
    onSurfaceVariant: '#2D5849',
    primary: '#1E8E6A',
    onPrimary: '#FFFFFF',
    primaryContainer: '#2CB387',
    onPrimaryContainer: '#F2FFF9',
    secondary: '#48806E',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#BDE3D5',
    onSecondaryContainer: '#1C4A3C',
    tertiary: '#E5A93C',
    tertiaryFixed: '#F7D99A',
    onTertiaryFixed: '#332100',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    border: '#0A1E17',
    divider: '#BDE3D5',
    shadow: '#0A1E17',
    cardBg: '#FFFFFF',
    accentSwatches: ['#56B4D3', '#A5E2E8', '#88D49E', '#F3C969'],
  },
  snow: {
    name: 'Snow (Kristal Salju)',
    weatherTitle: 'Bersalju Dingin',
    weatherDesc: 'Dingin, bersih, minimalis, dan tentram berselimut salju',
    weatherIcon: 'ac_unit',
    tempText: '2°C • Salju Halus',
    surface: '#F2F8FD',
    surfaceContainer: '#DDECFA',
    surfaceContainerLow: '#E8F3FD',
    surfaceContainerHigh: '#D0E3F6',
    surfaceContainerLowest: '#FFFFFF',
    surfaceDim: '#C2D9EE',
    onSurface: '#102231',
    onSurfaceVariant: '#39536B',
    primary: '#3076AB',
    onPrimary: '#FFFFFF',
    primaryContainer: '#4592CC',
    onPrimaryContainer: '#F5FAFF',
    secondary: '#55748F',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#C6DDF1',
    onSecondaryContainer: '#213E57',
    tertiary: '#6BBEEA',
    tertiaryFixed: '#BCE3F7',
    onTertiaryFixed: '#082D42',
    error: '#C0392B',
    onError: '#FFFFFF',
    border: '#0D1C28',
    divider: '#C6DDF1',
    shadow: '#0D1C28',
    cardBg: '#FFFFFF',
    accentSwatches: ['#EAF6FD', '#88CEEB', '#D4EFFC', '#3076AB'],
  },
};
